-- AlterTable
ALTER TABLE `bahan_baku` ADD COLUMN `foto_url` VARCHAR(255) NULL,
    ADD COLUMN `kategori` ENUM('TEPUNG', 'MINYAK', 'SAYURAN', 'BUMBU', 'DAGING', 'LAINNYA') NOT NULL DEFAULT 'LAINNYA';
